name: camara
description: A new Flutter project.

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  image_picker:
 
  cupertino_icons: ^0.1.2
  http: ^0.12.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
      - assets/img/
 
